### ISSUE TITLE
The library is compiled without QT support in function 

### ISSUE THREAD

**Issue by bytearchive** [alkasm/magicwand#5] opened 2022-06-19 18:07 UTC
Hi 
I am getting this while running your library
```
cv2.error: OpenCV(4.6.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/highgui/src/window.cpp:1190: error: (-213:The function/feature is not implemented) The library is compiled without QT support in function 'displayStatusBar'
```

**Comment by alkasm** [comment] 2022-06-19 19:30
This is a duplicate of #4

**Closed as not planned by alkasm** 2022-06-19 19:30 UTC
